---
title: "Correlated traits: Index selection"
author: "Jinliang Yang"
date: "Dec. 9th, 2019"
output:
  xaringan::moon_reader:
    css: ["default", "../../asset/unl-150.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

# The correlation between two traits

\begin{align*}
& r_P = r_Ah_Xh_Y + r_Ee_Xe_Y \\
\end{align*}

- __ $r_P$__: the phenotypic correlation between two traits X and Y
- __ $r_A$__: the genetic correlation due to breeding values between X and Y
- __ $r_E$__: the environmental correlation between X and Y, including non-additive genetic effects
- __ $h^2$__: heritability
- __ $e^2$__: $1-h^2$


__Genetic__ and __environmental correlation__ come together to create the phenotypic correlation.


---
# Correlated response to selection

### What is the expected BV of Y given a BV of X?

$b_{A_{YX}}  = r_A\frac{\sigma_{A_Y}}{\sigma_{A_X}}$ and $R_X = ih_X\sigma_{A_X}$, correlated response of trait Y is:

--

\begin{align*}
CR_Y &  =  b_{A_{YX}}R_X  \\
& = r_A \frac{\sigma_{A_Y}}{\sigma_{A_X}} ih_X\sigma_{A_X}\\
& = ih_Xr_A\sigma_{A_Y} \\
\end{align*}

--

Because $\sigma_{A_Y} = h_Y\sigma_{P_Y}$, therefore,

\begin{align*}
& CR_Y = ih_Xh_Yr_A\sigma_{P_Y} \\
\end{align*}

--

In the formula:
- $h_Xh_Yr_A$ is referred to as the __coheritability__, as it takes the place of the heritability in the direct response equation.

---

# Indirect selection

The trade-off between selection on a correlated trait and direct selection on a trait can also be seen:

\begin{align*}
\frac{CR_Y}{R_Y}  & =  \frac{i_Xh_Xr_A\sigma_{A_Y}}{i_Yh_Y\sigma_{A_Y}} \\
& = \frac{i_Xh_Xr_A}{i_Yh_Y}\\
\end{align*}

--

### Assuming seletion intensity is the same

- When __ $h_Xr_A > h_Y$__, a correlated response from selection on a secondary trait (X) is greater than response to direct selection on Y .

--

  - Note that this exact same property applies to usefulness of molecular markers for __marker-assisted selection__

---

# Indirect selection

The trade-off between selection on a correlated trait and direct selection on a trait can also be seen:

\begin{align*}
\frac{CR_Y}{R_Y}  & =  \frac{i_Xh_Xr_A\sigma_{A_Y}}{i_Yh_Y\sigma_{A_Y}} \\
& = \frac{i_Xh_Xr_A}{i_Yh_Y}\\
\end{align*}


### Practical considerations

- If trait Y is very __expensive__ and __difficult__ to measure, but trait X is very cheap and easy to measure.
  - e.g. high-throughput phenotyping techonologies

--

- Or the desired traits is measurable __in one sex__ only, but the secondary traits is measurable in both.
  - e.g. milk yield and body weight in dairy cow

---


# Indirect selection

The trade-off between selection on a correlated trait and direct selection on a trait can also be seen:

\begin{align*}
\frac{CR_Y}{R_Y}  & =  \frac{i_Xh_Xr_A\sigma_{A_Y}}{i_Yh_Y\sigma_{A_Y}} \\
& = \frac{i_Xh_Xr_A}{i_Yh_Y}\\
\end{align*}


### Genotype-by-environment interaction

- Performance in different environments can be regarded as __two separate, but correlated traits__.
 - Improvement in one environment by selection in another environment can be predicted by knowing the heritability in each environment and the genetic correlation between them.
 

---

# Selection on multiple traits

Total economic value is a composite of many traits. How does one __maximize response for many traits__ simultaneously?


--

#### Options for multiple trait selection

- __Tandom selection__: 
  - Selection for one trait at a time until that trait is improved to a desired level.
  - After that, selection proceeds for another trait.

--

- __Independent culling levels__: 
  - Only individuals that meet the minimum standard for each trait are selected.

--

- __Index selection__: 
  - Select for multiple traits simultaneously by constructing an index value.
  - Index value is then treated as a single economic trait.

---

# Genetic merit

- Any individual has a genetic value for what we'll call as __genetic merit__, or simply, __merit__.

--

  - Merit is the summation of all traits contributing to an individual's worth, fitness, economic value, etc.

--

#### The __true value of merit__ is represented as:

\begin{align*}
T & = a_1G_1 + a_2G_2 + ... + a_mGm \\
& = \sum_{i=1}^ma_iG_i \\
\end{align*}

- $G_i$ is the genetic value for trait $i$
- $a_i$ is the economic weight placed on trait $i$
  - The economic weights are set by the breeder according to production needs and value. 


---
# Index trait

To accurately predict genentic merit $T$, we want to combine the values of multiple traits into one value, denoted $I$. 

--

\begin{align*}
I & = b_1P_1 + b_2P_2 + ... + b_mPm \\
& = \sum_{i=1}^mb_iP_i \\
\end{align*}

- $P_i$ is the phenotypic value for trait $i$ that goes into the index
- $b_i$ is the weighting factor on trait $i$

--

### Correlation between T and I

The goal is to __find the values of the $b_i$s__ that could __maximize the correlations__ between $T$ and $I$, or $r_{TI}$.

\begin{align*}
r_{TI} = \frac{Cov(T, I)}{\sigma_T\sigma_I}
\end{align*}


---

# Correlation between T and I

\begin{align*}
r_{TI} = \frac{Cov(T, I)}{\sigma_T\sigma_I}
\end{align*}

Obtaining the maximum value of the correlation involves taking the derivative and setting to zero. 

--

Finally, we get:

\begin{align*}
{\begin{bmatrix}
Var(G_1) & Cov(G_1, G_2) & \cdots & Cov(G_m, G_1) \\
Cov(G_1, G_2) & Var(G_2) & \cdots & Cov(G_m, G_2) \\
\vdots & \vdots & \ddots & \vdots \\
Cov(G_1, G_m) & Cov(G_2, G_m) & \cdots & Var(G_m) \\
\end{bmatrix}}
{\begin{bmatrix}
a_1\\
a_2\\
\vdots \\
a_m\end{bmatrix}}
& = \\
{\begin{bmatrix}
Var(P_1) & Cov(P_1, P_2) & \cdots & Cov(P_m, P_1) \\
Cov(P_1, P_2) & Var(P_2) & \cdots & Cov(P_m, P_2) \\
\vdots & \vdots & \ddots & \vdots \\
Cov(P_1, P_m) & Cov(P_2, P_m) & \cdots & Var(P_m) \\
\end{bmatrix}}
{\begin{bmatrix}
b_1\\
b_2\\
\vdots \\
b_m\end{bmatrix}}
\end{align*}


---

### Matrix Notation

\begin{align*}
\mathbf{Ga} = \mathbf{Pb}
\end{align*}

- $\mathbf{P}$ is the phenotypic variance-covariance matrix
- $\mathbf{G}$ is the genetic variance-covariance matrix
- $\mathbf{a}$ is the vector of __known__ economic weights
- $\mathbf{b}$ is the vector of __unknow__ weights, or the weights to be applied to the phenotypic values of the different traits composing the index, $I$.

--

In matrix algebra, taking the inverse of a matrix and multiplying is equivalent to division in scalar algebra.

\begin{align*}
& \mathbf{Ga} = \mathbf{Pb} \\
& \mathbf{P^{-1}}\mathbf{Ga} = \mathbf{P^{-1}}\mathbf{Pb} \\
& \mathbf{P^{-1}}\mathbf{Ga} = \mathbf{b} \\
\end{align*}

---
# Optimum index

The vector of weights, which is called the __Smith-Hazel index__, or __optimum index__:

\begin{align*}
& \mathbf{b} = \mathbf{P^{-1}}\mathbf{Ga}  \\
\end{align*}


--

- The vector of $\mathbf{b}$ can be estimated if we know the __phenotypic and genetic variances__ and the __phenotypic and genetic covariances__

--

- This assumes that we have good information on the economic weights, which can be hard to determine.

--

- Then the resulting vector of weights will give a selection index that maximized genetic gain in $T$, the true genetic marit.


--

- The drawback of this index is that the genetic variance and covariances are often estimated with large amounts error, which may reduce the correlation between I and T.


???
# A problem

This litter size of mice could be increased: 
- 1) by selection of females for their little size
- 2) by selection of both parents for body weight

Which would be the better of these two simple procedures, given the following parameters?

- $h^2$ of litter size: 0.22
- $h^2$ of body weight: 0.35
- Genetic correlation $r_A$: 0.43
- Proportion of selection:
  - Females: 25% ( $i_f$ =1.271)
  - Males: 10% ( $i_m$ =1.755)

